/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package speakit.Petstore;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.apache.http.NameValuePair;
import speakit.Petstore.utils.HTTPClient;
import speakit.Petstore.utils.HTTPRequest;
import speakit.Petstore.utils.JSON;

public class Pets {
	
	private HTTPClient _defaultClient;
	private HTTPClient _securityClient;
	private String _serverUrl;
	private String _language;
	private String _sdkVersion;
	private String _genVersion;

	public Pets(HTTPClient defaultClient, HTTPClient securityClient, String serverUrl, String language, String sdkVersion, String genVersion) {
		this._defaultClient = defaultClient;
		this._securityClient = securityClient;
		this._serverUrl = serverUrl;
		this._language = language;
		this._sdkVersion = sdkVersion;
		this._genVersion = genVersion;
	}

    /**
     * Create a pet
     * @return the response from the API call
     * @throws Exception if the API call fails
     */
    public speakit.Petstore.models.operations.CreatePetsResponse createPets() throws Exception {
        String baseUrl = this._serverUrl;
        String url = speakit.Petstore.utils.Utils.generateURL(baseUrl, "/pets");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s", this._language, this._sdkVersion, this._genVersion));
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        speakit.Petstore.models.operations.CreatePetsResponse res = new speakit.Petstore.models.operations.CreatePetsResponse(contentType, httpRes.statusCode()) {{
            error = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 201) {
        }
        else {
            if (speakit.Petstore.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                speakit.Petstore.models.shared.Error out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), speakit.Petstore.models.shared.Error.class);
                res.error = out;
            }
        }

        return res;
    }

    /**
     * List all pets
     * @param request the request object containing all of the parameters for the API call
     * @return the response from the API call
     * @throws Exception if the API call fails
     */
    public speakit.Petstore.models.operations.ListPetsResponse listPets(speakit.Petstore.models.operations.ListPetsRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = speakit.Petstore.utils.Utils.generateURL(baseUrl, "/pets");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json;q=1, application/json;q=0");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s", this._language, this._sdkVersion, this._genVersion));
        java.util.List<NameValuePair> queryParams = speakit.Petstore.utils.Utils.getQueryParams(speakit.Petstore.models.operations.ListPetsRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        speakit.Petstore.models.operations.ListPetsResponse res = new speakit.Petstore.models.operations.ListPetsResponse(contentType, httpRes.statusCode()) {{
            pets = null;
            error = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            res.headers = httpRes.headers().map().keySet().stream().collect(Collectors.toMap(Function.identity(), k -> httpRes.headers().allValues(k).toArray(new String[0])));
            
            if (speakit.Petstore.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                speakit.Petstore.models.shared.Pet[] out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), speakit.Petstore.models.shared.Pet[].class);
                res.pets = out;
            }
        }
        else {
            if (speakit.Petstore.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                speakit.Petstore.models.shared.Error out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), speakit.Petstore.models.shared.Error.class);
                res.error = out;
            }
        }

        return res;
    }

    /**
     * Info for a specific pet
     * @param request the request object containing all of the parameters for the API call
     * @return the response from the API call
     * @throws Exception if the API call fails
     */
    public speakit.Petstore.models.operations.ShowPetByIdResponse showPetById(speakit.Petstore.models.operations.ShowPetByIdRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = speakit.Petstore.utils.Utils.generateURL(speakit.Petstore.models.operations.ShowPetByIdRequest.class, baseUrl, "/pets/{petId}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json;q=1, application/json;q=0");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s", this._language, this._sdkVersion, this._genVersion));
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        speakit.Petstore.models.operations.ShowPetByIdResponse res = new speakit.Petstore.models.operations.ShowPetByIdResponse(contentType, httpRes.statusCode()) {{
            pet = null;
            error = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (speakit.Petstore.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                speakit.Petstore.models.shared.Pet out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), speakit.Petstore.models.shared.Pet.class);
                res.pet = out;
            }
        }
        else {
            if (speakit.Petstore.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                speakit.Petstore.models.shared.Error out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), speakit.Petstore.models.shared.Error.class);
                res.error = out;
            }
        }

        return res;
    }
}