/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package speakit.Petstore;

import speakit.Petstore.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0.0-alpha.10";
	public String sdkVersion = "1.2.0";
	public String genVersion = "2.37.0";
	
}