/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package speakit.Petstore.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Pet - Expected response to a valid request
 */
public class Pet {
    @JsonProperty("id")
    public Long id;

    public Pet withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public Pet withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tag")
    public String tag;

    public Pet withTag(String tag) {
        this.tag = tag;
        return this;
    }
    
    public Pet(@JsonProperty("id") Long id, @JsonProperty("name") String name) {
        this.id = id;
        this.name = name;
  }
}
